language: ko-KR
reviews:
  auto_review:
    enabled: true
    ignore_title_keywords:
      - '[skip-review]'
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  fail_commit_status: true
  sequence_diagrams: false
  auto_apply_labels: true
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: false
